package api

import "context"

// Auth implements user related spec.
type Auth interface {
	// IsUsernameExists ...
	IsUsernameExists(ctx context.Context, username string) (bool, error)

	// IsEmailExists ...
	IsEmailExists(ctx context.Context, email string) (bool, error)

	// SaveNewUser ...
	SaveNewUser(ctx context.Context, user *User) error

	// LoadUser ...
	LoadUser(ctx context.Context, id int64) (*User, error)

	// LoadUserByUsernameOrEmail ...
	LoadUserByUsernameOrEmail(ctx context.Context, input string) (*User, error)

	// LoadUserByConfirmationToken ...
	LoadUserByConfirmationToken(ctx context.Context, token string) (*User, error)

	// LoadUserByRecoveryToken ...
	LoadUserByRecoveryToken(ctx context.Context, token string) (*User, error)

	// LoadUserByEmailChangeToken ...
	LoadUserByEmailChangeToken(ctx context.Context, token string) (*User, error)

	// Authenticate ...
	Authenticate(ctx context.Context, password string, user *User) error

	// ConfirmUser ...
	ConfirmUser(ctx context.Context, user *User) error

	// SetConfirmationToken ...
	SetConfirmationToken(ctx context.Context, confirm Confirmation, user *User) error

	// RecoverUser ...
	RecoverUser(ctx context.Context, user *User) error

	// SetRecoveryToken ...
	SetRecoveryToken(ctx context.Context, user *User) error

	// ConfirmEmailChange ...
	ConfirmEmailChange(ctx context.Context, user *User) error

	// SetEmailChangeToken ...
	SetEmailChangeToken(ctx context.Context, email string, user *User) error

	// UpdateUsername ...
	UpdateUsername(ctx context.Context, username string, user *User) error

	// UpdatePassword ...
	UpdatePassword(ctx context.Context, hash string, user *User) error

	// UpdateUserMetaData ...
	UpdateUserMetaData(ctx context.Context, data map[string]interface{}, user *User) error

	// UpdateAppMetaData ...
	UpdateAppMetaData(ctx context.Context, data map[string]interface{}, user *User) error
}
