name: Pull Request
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          MAILER_REGION: ${{ secrets.MAILER_REGION }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_SERVER_SECRET: ${{ secrets.TEST_SERVER_SECRET }}
          TEST_RECIPIENT: ${{ secrets.TEST_RECIPIENT }}
          TEST_FILE: ${{ secrets.TEST_FILE }}
          TEST_FILE_IN_FOLDER: ${{ secrets.TEST_FILE_IN_FOLDER }}
          TEST_PASSES_BUCKET: ${{ secrets.TEST_PASSES_BUCKET }}
          TEST_PROJECT: ${{ secrets.TEST_PROJECT }}
          TEST_TEMPLATES_BUCKET: ${{ secrets.TEST_TEMPLATES_BUCKET }}
        with:
          version: '1.12'
      - run: mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS test_okpock;' && make test
