name: Deploy Application
push:
  branches:
    - master
jobs:

  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

      - name: Set up MySQL database
        run: mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS test_okpock;'

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Get dependencies
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on
        run: make download

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          MAILER_REGION: ${{ secrets.MAILER_REGION }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_SERVER_SECRET: ${{ secrets.TEST_SERVER_SECRET }}
          TEST_RECIPIENT: ${{ secrets.TEST_RECIPIENT }}
          TEST_FILE: ${{ secrets.TEST_FILE }}
          TEST_FILE_IN_FOLDER: ${{ secrets.TEST_FILE_IN_FOLDER }}
          TEST_PASSES_BUCKET: ${{ secrets.TEST_PASSES_BUCKET }}
          TEST_PROJECT: ${{ secrets.TEST_PROJECT }}
          TEST_TEMPLATES_BUCKET: ${{ secrets.TEST_TEMPLATES_BUCKET }}
        run: make test

      - name: Build
        run: make release

      - name: Packing zip
        run: |
          zip -r ${GITHUB_SHA} ./bin -x '.git/*'
          mkdir -p build
          mv ${GITHUB_SHA}.zip build/gh-actions-${GITHUB_SHA}.zip
